name: Check Build and Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install LLVM 14
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-14

      - name: Configure with CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make -j 

      - name: Run test binary
        run: |
          cd build 
          ./test/test_abi
